// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70m9Nu8OKB03PsAWEbBmuGGlR69mi31o',
    appId: '1:978070940690:web:362f5d4f5253bb73c5bccb',
    messagingSenderId: '978070940690',
    projectId: 'chti-face-bouc-17027',
    authDomain: 'chti-face-bouc-17027.firebaseapp.com',
    storageBucket: 'chti-face-bouc-17027.firebasestorage.app',
    measurementId: 'G-XHX4DJF253',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC1RQBBs3LzSM_Jn5_5SbK4dIF4PdFgfk',
    appId: '1:978070940690:android:1504c29c1f038a20c5bccb',
    messagingSenderId: '978070940690',
    projectId: 'chti-face-bouc-17027',
    storageBucket: 'chti-face-bouc-17027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsdZldRPlQRVvyynWHjNdIfwCJ_gF5XII',
    appId: '1:978070940690:ios:ea35a25bc73f84ffc5bccb',
    messagingSenderId: '978070940690',
    projectId: 'chti-face-bouc-17027',
    storageBucket: 'chti-face-bouc-17027.firebasestorage.app',
    iosBundleId: 'com.example.projet2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsdZldRPlQRVvyynWHjNdIfwCJ_gF5XII',
    appId: '1:978070940690:ios:ea35a25bc73f84ffc5bccb',
    messagingSenderId: '978070940690',
    projectId: 'chti-face-bouc-17027',
    storageBucket: 'chti-face-bouc-17027.firebasestorage.app',
    iosBundleId: 'com.example.projet2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD70m9Nu8OKB03PsAWEbBmuGGlR69mi31o',
    appId: '1:978070940690:web:c2a7b7b7d920cd85c5bccb',
    messagingSenderId: '978070940690',
    projectId: 'chti-face-bouc-17027',
    authDomain: 'chti-face-bouc-17027.firebaseapp.com',
    storageBucket: 'chti-face-bouc-17027.firebasestorage.app',
    measurementId: 'G-7EWK8BQREX',
  );

}